# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Theme Settings
#
# Review documentation to determine if you should use `theme` or `remote_theme`
# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#installing-the-theme

# Theme Settings
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", etc.

# Site Settings
locale: "en-US"
title: "Personal Portfolio Website"
title_separator: "-"
name: "Ismail Otukoya"
description: "Data Scientist & Business Analyst in E-commerce and Retail"
url: "https://IsmailOtukoya.github.io"
baseurl: "" # Leave empty unless deploying to a subdirectory.
repository: "IsmailOtukoya/IsmailOtukoya.github.io"

# Author Information
author:
  name: "Ismail Otukoya"
  bio: "Enthusiastic Data Scientist & Business Analyst in E-commerce and Retail."
  location: "Lagos, Nigeria"
  email: "otukoyaismail@gmail.com"

# Social Links
social:
  type: "Person"
  name: "Ismail Otukoya"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/IsmailOtukoya"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/ismail-otukoya-89765521b/"

# Footer Links
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/IsmailOtukoya"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/ismail-otukoya-89765521b/"

# Plugins
plugins:
  - jekyll-paginate

# Pagination
paginate: 5
paginate_path: "/page:num/"

# Markdown and Highlighter
markdown: kramdown
highlighter: rouge

# Timezone
timezone: "Africa/Lagos"

# Outputting
permalink: "/:categories/:title/"
